/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MidiaRouteImport } from './routes/midia'
import { Route as DetalhamentoRouteImport } from './routes/detalhamento'
import { Route as IndexRouteImport } from './routes/index'

const MidiaRoute = MidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => rootRouteImport,
} as any)
const DetalhamentoRoute = DetalhamentoRouteImport.update({
  id: '/detalhamento',
  path: '/detalhamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detalhamento': typeof DetalhamentoRoute
  '/midia': typeof MidiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detalhamento': typeof DetalhamentoRoute
  '/midia': typeof MidiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detalhamento': typeof DetalhamentoRoute
  '/midia': typeof MidiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detalhamento' | '/midia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detalhamento' | '/midia'
  id: '__root__' | '/' | '/detalhamento' | '/midia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetalhamentoRoute: typeof DetalhamentoRoute
  MidiaRoute: typeof MidiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/midia': {
      id: '/midia'
      path: '/midia'
      fullPath: '/midia'
      preLoaderRoute: typeof MidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detalhamento': {
      id: '/detalhamento'
      path: '/detalhamento'
      fullPath: '/detalhamento'
      preLoaderRoute: typeof DetalhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetalhamentoRoute: DetalhamentoRoute,
  MidiaRoute: MidiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
